### ISSUE TITLE
TODO - Documentation Changes

### ISSUE THREAD

**Issue by Easelm** [ElunaLuaEngine/Eluna#101]
Use Rochet2's comment on this issue as an example on how to appropriately document. The comment structure is subject to change, be open to that.

We need to copy method documentation from LuaFunctions.cpp and paste them in a specific comment order (look at Rochet2's comment below) for the wiki above the method function itself.

I'll be working on doing this too, just letting everyone know. Also, here is the link to the new wiki: http://eluna.emudevs.com/

Current files that need to have this done:
 ~~AuraMethods.h~~
 ~~CorpseMethods.h~~
 ~~CreatureMethods.h~~
 ~~GameObjectMethods.h~~
 ~~GlobalMethods.h~~
 ~~GroupMethods.h~~
 ~~GuildMethods.h~~
~~ItemMethods.h~~
 ~~MapMethods.h~~
 ~~ObjectMethods.h~~
 ~~PlayerMethods.h~~
~~ElunaQueryMethods.h~~
 ~~QuestMethods.h~~
 ~~SpellMethods.h~~
 ~~UnitMethods.h~~
 ~~VehicleMethods.h~~
 ~~WeatherMethods.h~~
 ~~WorldObjectMethods.h~~
 ~~WorldPacketMethods.h~~

**Comment by Rochet2** [comment]
Here are some todo on the documentation:
- [ ] Add download button for offline use
- [ ] Possibly make search also search through the arguments and or description (short description?)
- [ ] Make argument names show on the class main page
- [ ] Fix the Global functions to show properly without Global: prefix everywhere or alter where they are (I like that they are grouped to global though)

**Comment by Easelm** [comment]
9d9e72e598b582ad7ad40ba84d9bf0828911f34c

Finished the rest of the documentation, or at least all I saw since most of these files are pretty big. Things left is to polish up documentation.
